<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>..\FileSurfer.Core\Assets\FileSurfer-logo.ico</ApplicationIcon>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <RootNamespace>FileSurfer.Windows</RootNamespace>
    <AssemblyName>FileSurfer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.18">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.18" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference
      Condition="'$(Configuration)' == 'Debug'"
      Include="Avalonia.Diagnostics"
      Version="11.3.18"
    />
    <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileSurfer.Core\FileSurfer.Core.csproj" />
  </ItemGroup>
</Project>
